const data = {
  categories: [
    { id: 1, name: 'Electronics' },
    { id: 2, name: 'Clothing' },
    { id: 3, name: 'Home & Kitchen' },
    { id: 4, name: 'Books' },
    { id: 5, name: 'Toys' },
    { id: 6, name: 'Sports' },
    { id: 7, name: 'Beauty' },
    { id: 8, name: 'Automotive' }
  ],
  products: [
    { id: 1, name: 'Smartphone', price: 699.99, originalPrice: 799.99, image: 'url1', category: 1, rating: 4.5, reviewCount: 150, description: 'Latest model smartphone.', tags: ['electronics', 'smartphone'], discount: 12.5, isOnSale: true, stock: 50 },
    { id: 2, name: 'Laptop', price: 1099.99, originalPrice: 1299.99, image: 'url2', category: 1, rating: 4.7, reviewCount: 200, description: 'High performance laptop.', tags: ['electronics', 'laptop'], discount: 15.4, isOnSale: true, stock: 30 },
    { id: 3, name: 'Headphones', price: 199.99, originalPrice: 249.99, image: 'url3', category: 1, rating: 4.2, reviewCount: 180, description: 'Comfortable over-ear headphones.', tags: ['electronics', 'headphones'], discount: 20.0, isOnSale: false, stock: 100 },
    { id: 4, name: 'T-shirt', price: 19.99, originalPrice: 25.99, image: 'url4', category: 2, rating: 4.6, reviewCount: 300, description: '100% cotton T-shirt.', tags: ['clothing', 'tshirt'], discount: 23.1, isOnSale: true, stock: 200 },
    { id: 5, name: 'Jeans', price: 49.99, originalPrice: 59.99, image: 'url5', category: 2, rating: 4.5, reviewCount: 240, description: 'Stylish jeans.', tags: ['clothing', 'jeans'], discount: 16.7, isOnSale: true, stock: 150 },
    { id: 6, name: 'Blender', price: 39.99, originalPrice: 49.99, image: 'url6', category: 3, rating: 4.3, reviewCount: 120, description: 'High-speed blender.', tags: ['home', 'kitchen', 'appliances'], discount: 20.0, isOnSale: true, stock: 80 },
    { id: 7, name: 'Cookbook', price: 29.99, originalPrice: 34.99, image: 'url7', category: 4, rating: 4.8, reviewCount: 90, description: 'Collection of delicious recipes.', tags: ['books', 'cookbook'], discount: 14.3, isOnSale: false, stock: 60 },
    { id: 8, name: 'Lego Set', price: 59.99, originalPrice: 69.99, image: 'url8', category: 5, rating: 4.9, reviewCount: 210, description: 'Fun Lego building set.', tags: ['toys', 'lego'], discount: 14.3, isOnSale: true, stock: 40 },
    { id: 9, name: 'Soccer Ball', price: 25.99, originalPrice: 30.99, image: 'url9', category: 6, rating: 4.6, reviewCount: 150, description: 'Official size soccer ball.', tags: ['sports', 'soccer'], discount: 16.6, isOnSale: true, stock: 90 },
    { id: 10, name: 'Beauty Kit', price: 89.99, originalPrice: 99.99, image: 'url10', category: 7, rating: 4.4, reviewCount: 110, description: 'Complete beauty kit for skincare.', tags: ['beauty', 'skincare'], discount: 10.0, isOnSale: false, stock: 35 },
    { id: 11, name: 'Car Wax', price: 19.99, originalPrice: 23.99, image: 'url11', category: 8, rating: 4.5, reviewCount: 75, description: 'High-quality car wax.', tags: ['automotive', 'car care'], discount: 16.7, isOnSale: true, stock: 100 }, // additional product data...  
    { id: 12, name: 'Gaming Console', price: 499.99, originalPrice: 599.99, image: 'url12', category: 1, rating: 4.8, reviewCount: 500, description: 'Next-gen gaming console.', tags: ['electronics', 'gaming'], discount: 16.7, isOnSale: true, stock: 75 },
    { id: 13, name: 'Dress', price: 39.99, originalPrice: 49.99, image: 'url13', category: 2, rating: 4.7, reviewCount: 130, description: 'Stylish dress for parties.', tags: ['clothing', 'dress'], discount: 20.0, isOnSale: false, stock: 80 },
    { id: 14, name: 'Microwave Oven', price: 89.99, originalPrice: 109.99, image: 'url14', category: 3, rating: 4.6, reviewCount: 85, description: 'Compact microwave oven.', tags: ['home', 'kitchen'], discount: 18.2, isOnSale: true, stock: 50 },
    { id: 15, name: 'Novel', price: 14.99, originalPrice: 19.99, image: 'url15', category: 4, rating: 4.3, reviewCount: 160, description: 'Bestselling novel.', tags: ['books', 'bestseller'], discount: 25.1, isOnSale: true, stock: 100 },
    { id: 16, name: 'Puzzle', price: 24.99, originalPrice: 29.99, image: 'url16', category: 5, rating: 4.5, reviewCount: 140, description: 'Challenging jigsaw puzzle.', tags: ['toys', 'puzzle'], discount: 16.7, isOnSale: false, stock: 60 },
    { id: 17, name: 'Tennis Racket', price: 59.99, originalPrice: 69.99, image: 'url17', category: 6, rating: 4.6, reviewCount: 50, description: 'Quality tennis racket.', tags: ['sports', 'tennis'], discount: 14.3, isOnSale: true, stock: 30 },
    { id: 18, name: 'Facial Cream', price: 29.99, originalPrice: 39.99, image: 'url18', category: 7, rating: 4.4, reviewCount: 95, description: 'Hydrating facial cream.', tags: ['beauty', 'skincare'], discount: 25.0, isOnSale: false, stock: 40 },
    { id: 19, name: 'Car Vacuum', price: 49.99, originalPrice: 59.99, image: 'url19', category: 8, rating: 4.5, reviewCount: 80, description: 'Portable car vacuum.', tags: ['automotive', 'car care'], discount: 16.7, isOnSale: false, stock: 75 },
    { id: 20, name: 'Smart Watch', price: 199.99, originalPrice: 249.99, image: 'url20', category: 1, rating: 4.7, reviewCount: 160, description: 'Fitness tracker smart watch.', tags: ['electronics', 'smartwatch'], discount: 20.0, isOnSale: true, stock: 90 },
    { id: 21, name: 'Sweater', price: 39.99, originalPrice: 49.99, image: 'url21', category: 2, rating: 4.8, reviewCount: 120, description: 'Warm and cozy sweater.', tags: ['clothing', 'sweater'], discount: 20.0, isOnSale: true, stock: 60 },
    { id: 22, name: 'Cooking Pot', price: 49.99, originalPrice: 59.99, image: 'url22', category: 3, rating: 4.5, reviewCount: 100, description: 'Durable cooking pot.', tags: ['home', 'kitchen'], discount: 16.7, isOnSale: true, stock: 80 },
    { id: 23, name: 'Children Book', price: 12.99, originalPrice: 15.99, image: 'url23', category: 4, rating: 4.6, reviewCount: 110, description: 'Engaging story for kids.', tags: ['books', 'children'], discount: 18.9, isOnSale: false, stock: 200 },
    { id: 24, name: 'Action Figure', price: 29.99, originalPrice: 34.99, image: 'url24', category: 5, rating: 4.8, reviewCount: 150, description: 'Collectible action figure.', tags: ['toys', 'collectible'], discount: 14.3, isOnSale: true, stock: 75 },
    { id: 25, name: 'Baseball Bat', price: 49.99, originalPrice: 59.99, image: 'url25', category: 6, rating: 4.5, reviewCount: 60, description: 'Durable baseball bat.', tags: ['sports', 'baseball'], discount: 16.7, isOnSale: false, stock: 40 },
    { id: 26, name: 'Shampoo', price: 15.99, originalPrice: 19.99, image: 'url26', category: 7, rating: 4.7, reviewCount: 80, description: 'Gentle cleansing shampoo.', tags: ['beauty', 'haircare'], discount: 20.0, isOnSale: true, stock: 100 },
    { id: 27, name: 'Jump Starter', price: 39.99, originalPrice: 49.99, image: 'url27', category: 8, rating: 4.3, reviewCount: 95, description: 'Portable jump starter for cars.', tags: ['automotive', 'car care'], discount: 20.0, isOnSale: false, stock: 30 },
    { id: 28, name: 'Tablet', price: 299.99, originalPrice: 399.99, image: 'url28', category: 1, rating: 4.6, reviewCount: 300, description: 'Lightweight tablet.', tags: ['electronics', 'tablet'], discount: 25.0, isOnSale: true, stock: 70 },
    { id: 29, name: 'Laptop Bag', price: 49.99, originalPrice: 59.99, image: 'url29', category: 2, rating: 4.4, reviewCount: 85, description: 'Stylish laptop bag.', tags: ['clothing', 'accessory'], discount: 16.7, isOnSale: true, stock: 110 },
    { id: 30, name: 'Food Processor', price: 89.99, originalPrice: 109.99, image: 'url30', category: 3, rating: 4.8, reviewCount: 70, description: 'Efficient food processor.', tags: ['home', 'kitchen'], discount: 18.2, isOnSale: false, stock: 50 },
    { id: 31, name: 'Textbook', price: 59.99, originalPrice: 69.99, image: 'url31', category: 4, rating: 4.0, reviewCount: 60, description: 'Comprehensive textbook.', tags: ['books', 'academic'], discount: 14.3, isOnSale: true, stock: 30 },
    { id: 32, name: 'Board Game', price: 39.99, originalPrice: 49.99, image: 'url32', category: 5, rating: 4.4, reviewCount: 130, description: 'Fun family board game.', tags: ['toys', 'game'], discount: 20.0, isOnSale: false, stock: 100 },
    { id: 33, name: 'Yoga Mat', price: 29.99, originalPrice: 34.99, image: 'url33', category: 6, rating: 4.6, reviewCount: 95, description: 'Non-slip yoga mat.', tags: ['sports', 'fitness'], discount: 14.3, isOnSale: true, stock: 60 },
    { id: 34, name: 'Nail Polish', price: 9.99, originalPrice: 14.99, image: 'url34', category: 7, rating: 4.8, reviewCount: 50, description: 'Long-lasting nail polish.', tags: ['beauty', 'cosmetics'], discount: 33.4, isOnSale: false, stock: 70 },
    { id: 35, name: 'Tire Pressure Gauge', price: 14.99, originalPrice: 19.99, image: 'url35', category: 8, rating: 4.5, reviewCount: 90, description: 'Accurate tire pressure gauge.', tags: ['automotive', 'accessory'], discount: 25.0, isOnSale: true, stock: 60 },
    { id: 36, name: 'Wireless Mouse', price: 29.99, originalPrice: 39.99, image: 'url36', category: 1, rating: 4.6, reviewCount: 110, description: 'Ergonomic wireless mouse.', tags: ['electronics', 'accessory'], discount: 25.0, isOnSale: false, stock: 80 },
    { id: 37, name: 'Socks', price: 9.99, originalPrice: 12.99, image: 'url37', category: 2, rating: 4.5, reviewCount: 70, description: 'Comfortable cotton socks.', tags: ['clothing', 'accessory'], discount: 23.1, isOnSale: true, stock: 150 },
    { id: 38, name: 'Rice Cooker', price: 49.99, originalPrice: 59.99, image: 'url38', category: 3, rating: 4.4, reviewCount: 65, description: 'Simple rice cooker.', tags: ['home', 'kitchen'], discount: 16.7, isOnSale: false, stock: 40 },
    { id: 39, name: 'Biography', price: 15.99, originalPrice: 19.99, image: 'url39', category: 4, rating: 4.5, reviewCount: 80, description: 'Insightful biography.', tags: ['books', 'nonfiction'], discount: 20.0, isOnSale: true, stock: 90 },
    { id: 40, name: 'Toy Car', price: 14.99, originalPrice: 19.99, image: 'url40', category: 5, rating: 4.3, reviewCount: 45, description: 'Fun toy car.', tags: ['toys', 'auto'], discount: 25.0, isOnSale: false, stock: 120 },
    { id: 41, name: 'Fitness Tracker', price: 99.99, originalPrice: 129.99, image: 'url41', category: 6, rating: 4.8, reviewCount: 90, description: 'Wearable fitness tracker.', tags: ['sports', 'fitness'], discount: 23.1, isOnSale: true, stock: 60 },
    { id: 42, name: 'Lipstick', price: 19.99, originalPrice: 24.99, image: 'url42', category: 7, rating: 4.6, reviewCount: 150, description: 'High-quality lipstick.', tags: ['beauty', 'cosmetics'], discount: 20.0, isOnSale: true, stock: 80 },
    { id: 43, name: 'Car Seat Cover', price: 29.99, originalPrice: 39.99, image: 'url43', category: 8, rating: 4.5, reviewCount: 70, description: 'Durable car seat cover.', tags: ['automotive', 'accessory'], discount: 25.0, isOnSale: false, stock: 90 },
    { id: 44, name: 'Smart Speaker', price: 149.99, originalPrice: 199.99, image: 'url44', category: 1, rating: 4.7, reviewCount: 180, description: 'Smart speaker with voice control.', tags: ['electronics', 'smart home'], discount: 25.0, isOnSale: true, stock: 40 },
    { id: 45, name: 'Skirt', price: 34.99, originalPrice: 39.99, image: 'url45', category: 2, rating: 4.3, reviewCount: 50, description: 'Stylish skirt for casual wear.', tags: ['clothing', 'skirt'], discount: 12.5, isOnSale: true, stock: 75 },
    { id: 46, name: 'Air Fryer', price: 79.99, originalPrice: 99.99, image: 'url46', category: 3, rating: 4.9, reviewCount: 110, description: 'Healthy cooking air fryer.', tags: ['home', 'kitchen'], discount: 20.0, isOnSale: false, stock: 20 },
    { id: 47, name: 'Science Fiction Novel', price: 19.99, originalPrice: 24.99, image: 'url47', category: 4, rating: 4.6, reviewCount: 65, description: 'Fascinating sci-fi novel.', tags: ['books', 'fiction'], discount: 20.0, isOnSale: true, stock: 50 },
    { id: 48, name: 'Children's Puzzle', price: 29.99, originalPrice: 34.99, image: 'url48', category: 5, rating: 4.5, reviewCount: 30, description: 'Puzzle for little kids.', tags: ['toys', 'children'], discount: 14.3, isOnSale: false, stock: 100 }
  ]
};

export default data;